JAR_FILE=$(dirname $BASH_SOURCE)/../metasys-cloudconnector-app.jar
$SERVICE_NAME=Metasys

#Slack Notifications
#SLACK_ALERT_PROD=https://hooks.slack.com/services/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
SLACK_ALERT_PROD=https://hooks.slack.com/services/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
SLACK_INFO_PROD=https://hooks.slack.com/services/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
